---
title: "Choline meta-analysis combining FEP, SCZ and NOS into psychosis group"
output: html_document
date: "October 2024"
---
install.packages("metafor")
install.packages("readcsv")
install.packages("ggplot2")
install.packages("RColorBrewer")
install.packages("writexl")

```{r}
setwd("~/Documents/Medicine/Research/Psychosis/MRS Choline in Psychosis/master_xls")

library(tidyverse) 
library(metafor) 
library(readxl)
library(RColorBrewer)
library(writexl) 

```

```{r}

# this section will clean and group FEP, Schizophrenia and Unspecified psychoses
# skip this section and just load the merged.xlsx in the next section if you have it

# --------
# df <- read_excel("established_psychosis.xls") old pre Jack's study IDs
df <- read_excel("established_psychosis_studyid.xls") 

# Load data for PFC combined estimates 
# df <- read_excel("master_xls/established_psychosis_pfc.xls") 

# Cleaning data -----

# Convert cols to numeric type
cols_to_numeric <- c('metabolite mean (bilateral)', 
                     'sd (bilateral)',
                     'metabolite mean (right)', 
                     'sd (right)', 
                     'metabolite mean (left)', 
                     'sd (left)', 
                     'sample_size')

merged_df <- df %>% 
  mutate(across(all_of(cols_to_numeric), ~as.numeric(as.character(.)))) 

# Convert all metabolites to 'Choline'
metab <- c('Choline', 'Cho + PCh', 'Cho/Cr', 'GPC + PCh', 'GPC + PCh/Cr', 'Cho/Water')

merged_df <- merged_df %>% mutate(metabolite = case_when( metabolite %in% c('Cho + PCh', 
                                                              'Cho/Cr', 
                                                              'GPC + PCh', 
                                                              'GPC + PCh/Cr',
                                                              'Cho/cr', 
                                                              'Cho/cre',
                                                              'Cho + PCh',
                                                              'Cho/Water',
                                                              'Choline/Cr') ~ 'Choline', TRUE ~
                                              metabolite ))

# Combine metabolites all to one column (bilateral from right and left)
merged_df <- merged_df %>% mutate(
  `metabolite mean (bilateral)` = ifelse(
    is.na(`metabolite mean (bilateral)`) & !is.na(`metabolite mean (right)`) & !is.na(`metabolite mean (left)`),
    ((`metabolite mean (right)` * `sample_size` + `metabolite mean (left)` * `sample_size`) / 
     (2 * `sample_size`)),
    `metabolite mean (bilateral)`
  )
)

# when only left
merged_df <- merged_df %>% mutate(`metabolite mean (bilateral)` =
ifelse(is.na(`metabolite mean (bilateral)`) &
is.na(`metabolite mean (right)`) &
!is.na(`metabolite mean (left)`),`metabolite mean (left)`,`metabolite mean (bilateral)`))

# when only right
merged_df <- merged_df %>% mutate(`metabolite mean (bilateral)` =
ifelse(is.na(`metabolite mean (bilateral)`) &
!is.na(`metabolite mean (right)`) &
is.na(`metabolite mean (left)`),`metabolite mean (right)`,`metabolite mean (bilateral)`))

# remove columns for R and L
merged_df <- merged_df %>% select(-`metabolite mean (right)`,
-`metabolite mean (left)`)

# standard deviation calculations
merged_df <- merged_df %>% mutate( `sd (bilateral)` = case_when(
is.na(`sd (bilateral)`) & is.na(`sd (right)`) & !is.na(`sd (left)`) ~
`sd (left)`, is.na(`sd (bilateral)`) & is.na(`sd (left)`) &
!is.na(`sd (right)`) ~ `sd (right)`, TRUE ~ `sd (bilateral)` ) ) %>%
mutate( `sd (bilateral)` = ifelse(is.na(`sd (bilateral)`) &
!is.na(`sd (right)`) & !is.na(`sd (left)`), sqrt((1/4) *
`sd (right)`^2 + (1/4) * `sd (left)`^2 + (1/2) * 0.8 * `sd (right)`
* `sd (left)`), `sd (bilateral)` ) )

# remove columns for R and L
merged_df <- merged_df %>% select(-`sd (right)`,
-`sd (left)`)

merged_df <- merged_df %>%
  mutate(
    region = case_when(
      region %in% c("Frontal white matter", "frontal white matter") ~ "Frontal white matter",
      region %in% c("White matter (multiple locations)") ~ "Global white matter",
      region %in% c("Grey matter (multiple locations)") ~ "Global grey matter",
      TRUE ~ region
    ),
      diagnosis = case_when(
      diagnosis %in% c("FEP", "Schizophrenia", "Unspecified psychosis") ~ "Psychosis",
      TRUE ~ diagnosis
    ))

# if you want to combine prefrontal - we are no longer doing this 
# merged_df <- merged_df %>% mutate(region = case_when(region %in% c("dlPFC", "mPFC", "Other frontal lobe") ~"Prefrontal",TRUE ~ region))

#-------------

```


``` {r} 

# Clinically High Risk Populations - Meta analysis -------

# Create dataframes to store overall SMD, CVR, and VR results
chr_smd_summary_results <- data.frame(
  brain_region = character(),
  diagnosis = character(),
  yi = numeric(),
  ci.lb = numeric(),
  ci.ub = numeric(),
  p_value = numeric(),
  I2 = numeric(),
  total_cases = numeric(),
  total_controls = numeric(),
  num_studies = integer(),
  stringsAsFactors = FALSE
)

chr_cvr_summary_results <- data.frame(
  brain_region = character(),
  diagnosis = character(),
  yi = numeric(),
  ci.lb = numeric(),
  ci.ub = numeric(),
  p_value = numeric(),
  I2 = numeric(),
  total_cases = numeric(),
  total_controls = numeric(),
  num_studies = integer(),
  stringsAsFactors = FALSE
)

chr_vr_summary_results <- data.frame(
  brain_region = character(),
  diagnosis = character(),
  yi = numeric(),
  ci.lb = numeric(),
  ci.ub = numeric(),
  p_value = numeric(),
  I2 = numeric(),
  total_cases = numeric(),
  total_controls = numeric(),
  num_studies = integer(),
  stringsAsFactors = FALSE
)

# Setting up loop variables ----

# unique brain regions
regions <- unique(merged_df$region)

# Create a folder to save the plots
output_folder <- "chr_forest_plots"
if (!dir.exists(output_folder)) {
  dir.create(output_folder)
}

# Loop over each brain region
for (current_reg in regions) {
  cat("Processing brain region:", current_reg, "\n")
  
  # Subset data for the current brain region
  current_df <- merged_df %>%
    filter(region == current_reg) %>%
    filter(diagnosis %in% c('HC', 'UHR/CHR')) %>%
    select(diagnosis, ID, metabolite, region, 
           `metabolite mean (bilateral)`, `sd (bilateral)`, sample_size, `First Author`)

  # Check if there are at least two unique studies for each diagnosis
  study_count <- current_df %>%
    group_by(diagnosis) %>%
    summarise(n_studies = n_distinct(ID)) %>%
    filter(n_studies >= 2)

  # If there are fewer than 2 studies for either diagnosis, skip this region
  if (nrow(study_count) < 2) {
    cat("Skipping brain region:", current_reg, "due to insufficient studies with complete data.\n")
    next
  }
  
  current_df <- current_df %>%
    group_by(ID) %>%
    filter(all(c("HC", "UHR/CHR") %in% diagnosis)) %>%
    ungroup()

  # Pivot the data and drop rows if any missing data
  current_df <- current_df %>%
    pivot_wider(names_from = diagnosis, values_from = c(`metabolite mean (bilateral)`, `sd (bilateral)`, sample_size, `First Author`)) %>%
    na.omit()

  # Drop rows with only healthy controls
  if ("metabolite mean (bilateral)_UHR/CHR" %in% colnames(current_df)) {
    current_df <- current_df %>%
      filter(!is.na(`metabolite mean (bilateral)_UHR/CHR`) | `metabolite mean (bilateral)_UHR/CHR` != "NULL")
  }

  # Check if the data frame is empty
  if (nrow(current_df) == 0) { 
    cat("Skipping brain region:", current_reg, "due to no data available.\n") 
  } else { 
    # Calculate total cases, controls, and number of studies
    total_cases <- sum(current_df$`sample_size_UHR/CHR`, na.rm = TRUE)
    total_controls <- sum(current_df$`sample_size_HC`, na.rm = TRUE)
    num_studies <- nrow(current_df)

    # Calculate SMD effect size using escalc
    escalc_smd_results <- escalc(measure = "SMD", 
                                 m1i=current_df$`metabolite mean (bilateral)_UHR/CHR`,
                                 sd1i=current_df$`sd (bilateral)_UHR/CHR`,
                                 m2i=current_df$`metabolite mean (bilateral)_HC`,
                                 sd2i=current_df$`sd (bilateral)_HC`,
                                 n1i=current_df$`sample_size_UHR/CHR`,
                                 n2i=current_df$`sample_size_HC`)
    current_df_smd <- cbind(current_df, escalc_smd_results)

    # Meta-analyze SMD
    smd_result <- rma(yi, vi, data = current_df_smd)
    
    # Store SMD results
    chr_smd_summary_results <- rbind(chr_smd_summary_results, data.frame(
      brain_region = current_reg,
      diagnosis = "CHR",
      yi = smd_result$beta[1],
      ci.lb = smd_result$ci.lb[1],
      ci.ub = smd_result$ci.ub[1],
      p_value = smd_result$pval,
      I2 = smd_result$I2,
      total_cases = total_cases,
      total_controls = total_controls,
      num_studies = num_studies,
      stringsAsFactors = FALSE
    ))
    
    # Save SMD plot
    smd_plot_path <- file.path(output_folder, paste0("SMD_", current_reg, ".png"))
    png(smd_plot_path, width = 800, height = 600)
    forest(smd_result, 
           slab = current_df_smd$`First Author_HC`, 
           xlab = "Standardized Mean Difference (SMD)", 
           main = paste("Forest Plot for SMD in", current_reg, "-", "CHR vs HC"))
    dev.off()

    # Calculate CVR using escalc
    escalc_cvr_results <- escalc(measure = "CVR", 
                                 m1i=current_df$`metabolite mean (bilateral)_UHR/CHR`,
                                 sd1i=current_df$`sd (bilateral)_UHR/CHR`,
                                 n1i=current_df$`sample_size_UHR/CHR`,
                                 m2i=current_df$`metabolite mean (bilateral)_HC`,
                                 sd2i=current_df$`sd (bilateral)_HC`,
                                 n2i=current_df$`sample_size_HC`)
    current_df_cvr <- cbind(current_df, escalc_cvr_results)

    # Meta-analyze CVR
    cvr_result <- rma(yi, vi, data = current_df_cvr)

    # Store CVR results
    chr_cvr_summary_results <- rbind(chr_cvr_summary_results, data.frame(
      brain_region = current_reg,
      diagnosis = "CHR",
      yi = cvr_result$beta[1],
      ci.lb = cvr_result$ci.lb[1],
      ci.ub = cvr_result$ci.ub[1],
      p_value = cvr_result$pval,
      I2 = cvr_result$I2,
      total_cases = total_cases,
      total_controls = total_controls,
      num_studies = num_studies,
      stringsAsFactors = FALSE
    ))

    # Save CVR plot
    cvr_plot_path <- file.path(output_folder, paste0("CVR_", current_reg, ".png"))
    png(cvr_plot_path, width = 800, height = 600)
    forest(cvr_result, 
           slab = current_df_cvr$`First Author_HC`, 
           xlab = "Coefficient of Variation Ratio (CVR)", 
           main = paste("Forest Plot for CVR in", current_reg, "-", "CHR vs HC"))
    dev.off()

    # Calculate VR using escalc
    escalc_vr_results <- escalc(measure = "VR", 
                                 m1i=current_df$`metabolite mean (bilateral)_UHR/CHR`,
                                 sd1i=current_df$`sd (bilateral)_UHR/CHR`,
                                 n1i=current_df$`sample_size_UHR/CHR`,
                                 m2i=current_df$`metabolite mean (bilateral)_HC`,
                                 sd2i=current_df$`sd (bilateral)_HC`,
                                 n2i=current_df$`sample_size_HC`)
    current_df_vr <- cbind(current_df, escalc_vr_results)

    # Meta-analyze VR
    vr_result <- rma(yi, vi, data = current_df_vr)

    # Store VR results
    chr_vr_summary_results <- rbind(chr_vr_summary_results, data.frame(
      brain_region = current_reg,
      diagnosis = "CHR",
      yi = vr_result$beta[1],
      ci.lb = vr_result$ci.lb[1],
      ci.ub = vr_result$ci.ub[1],
      p_value = vr_result$pval,
      I2 = vr_result$I2,
      total_cases = total_cases,
      total_controls = total_controls,
      num_studies = num_studies,
      stringsAsFactors = FALSE
    ))

    # Save VR plot
    vr_plot_path <- file.path(output_folder, paste0("VR_", current_reg, ".png"))
    png(vr_plot_path, width = 800, height = 600)
    forest(vr_result, 
           slab = current_df_vr$`First Author_HC`, 
           xlab = "Variance Ratio (VR)", 
           main = paste("Forest Plot for VR in", current_reg, "-", "CHR vs HC"))
    dev.off()
  } 
}



# Remove duplicate study rows if any
chr_smd_summary_results <- chr_smd_summary_results %>% distinct()
chr_cvr_summary_results <- chr_cvr_summary_results %>% distinct()
chr_vr_summary_results <- chr_vr_summary_results %>% distinct()

# Print the summary of meta-analysis results
print(chr_smd_summary_results)
print(chr_cvr_summary_results)
print(chr_vr_summary_results)

# Save the summary data frames to Excel files if needed
write_xlsx(chr_smd_summary_results, path = "chr_smd_results.xlsx")
write_xlsx(chr_cvr_summary_results, path = "chr_cvr_results.xlsx")
write_xlsx(chr_vr_summary_results, path = "chr_vr_results.xlsx")

# not enough for Egger's
```

```{r}

# Combined Psychosis Group - Meta analysis -------

# Create dataframes to store overall SMD, CVR, and VR results
psych_smd_summary_results <- data.frame(
  brain_region = character(),
  diagnosis = character(),
  yi = numeric(),
  ci.lb = numeric(),
  ci.ub = numeric(),
  p_value = numeric(),
  I2 = numeric(),
  total_cases = numeric(),
  total_controls = numeric(),
  num_studies = integer(),
  stringsAsFactors = FALSE
)

psych_cvr_summary_results <- data.frame(
  brain_region = character(),
  diagnosis = character(),
  yi = numeric(),
  ci.lb = numeric(),
  ci.ub = numeric(),
  p_value = numeric(),
  I2 = numeric(),
  total_cases = numeric(),
  total_controls = numeric(),
  num_studies = integer(),
  stringsAsFactors = FALSE
)

psych_vr_summary_results <- data.frame(
  brain_region = character(),
  diagnosis = character(),
  yi = numeric(),
  ci.lb = numeric(),
  ci.ub = numeric(),
  p_value = numeric(),
  I2 = numeric(),
  total_cases = numeric(),
  total_controls = numeric(),
  num_studies = integer(),
  stringsAsFactors = FALSE
)

# Setting up loop variables
reg <- unique(merged_df$region)

diagnoses <- c('Psychosis', 'HC')

# Create a folder to save the plots
output_folder <- "psychosis_forest_plots"
if (!dir.exists(output_folder)) {
  dir.create(output_folder)
}

# Loop over each brain region
for (current_reg in reg) {
  cat("Processing brain region:", current_reg, "\n")
  
  # Subset data for the current brain region
  current_df <- merged_df %>%
    filter(region == current_reg, diagnosis %in% diagnoses) %>%
    select(diagnosis, ID, `First Author`, metabolite, region, 
           `metabolite mean (bilateral)`, `sd (bilateral)`, sample_size)

  current_df <- current_df %>%
    group_by(ID) %>%
    filter(all(c("HC", "Psychosis") %in% diagnosis)) %>%
    ungroup() %>%
    pivot_wider(names_from = diagnosis, values_from = c(`metabolite mean (bilateral)`, `sd (bilateral)`, sample_size, `First Author`)) %>%
    na.omit()

  # Skip if there are insufficient studies
  if (nrow(current_df) < 2) { 
    cat("Skipping brain region:", current_reg, "due to insufficient data.\n")
    next
  }

  # Calculate total cases, controls, and number of studies
  total_cases <- sum(current_df$`sample_size_Psychosis`, na.rm = TRUE)
  total_controls <- sum(current_df$`sample_size_HC`, na.rm = TRUE)
  num_studies <- nrow(current_df)

  # SMD meta-analysis
  escalc_smd_results <- escalc(measure = "SMD", 
                               m1i = current_df$`metabolite mean (bilateral)_Psychosis`,
                               sd1i = current_df$`sd (bilateral)_Psychosis`,
                               m2i = current_df$`metabolite mean (bilateral)_HC`,
                               sd2i = current_df$`sd (bilateral)_HC`,
                               n1i = current_df$`sample_size_Psychosis`,
                               n2i = current_df$`sample_size_HC`)
  current_df_smd <- cbind(current_df, escalc_smd_results)
  smd_result <- rma(yi, vi, data = current_df_smd)
  
  # Store SMD results
  psych_smd_summary_results <- rbind(psych_smd_summary_results, data.frame(
    brain_region = current_reg,
    diagnosis = "Established Psychosis",
    yi = smd_result$beta[1],
    ci.lb = smd_result$ci.lb[1],
    ci.ub = smd_result$ci.ub[1],
    p_value = smd_result$pval,
    I2 = smd_result$I2,
    total_cases = total_cases,
    total_controls = total_controls,
    num_studies = num_studies,
    stringsAsFactors = FALSE
  ))

  # Save SMD plot
  smd_plot_path <- file.path(output_folder, paste0("SMD_", current_reg, ".png"))
  png(smd_plot_path, width = 800, height = 600)
  forest(smd_result, 
         slab = current_df_smd$`First Author_HC`, 
         xlab = "Standardized Mean Difference (SMD)", 
         main = paste("Forest Plot for SMD in", current_reg, "-", "Established Psychosis vs HC"))
  dev.off()

  # CVR meta-analysis
  escalc_cvr_results <- escalc(measure = "CVR", 
                               m1i = current_df$`metabolite mean (bilateral)_Psychosis`,
                               sd1i = current_df$`sd (bilateral)_Psychosis`,
                               n1i = current_df$`sample_size_Psychosis`,
                               m2i = current_df$`metabolite mean (bilateral)_HC`,
                               sd2i = current_df$`sd (bilateral)_HC`,
                               n2i = current_df$`sample_size_HC`)
  current_df_cvr <- cbind(current_df, escalc_cvr_results)
  cvr_result <- rma(yi, vi, data = current_df_cvr)

  # Store CVR results
  psych_cvr_summary_results <- rbind(psych_cvr_summary_results, data.frame(
    brain_region = current_reg,
    diagnosis = "Established Psychosis",
    yi = cvr_result$beta[1],
    ci.lb = cvr_result$ci.lb[1],
    ci.ub = cvr_result$ci.ub[1],
    p_value = cvr_result$pval,
    I2 = cvr_result$I2,
    total_cases = total_cases,
    total_controls = total_controls,
    num_studies = num_studies,
    stringsAsFactors = FALSE
  ))

  # Save CVR plot
  cvr_plot_path <- file.path(output_folder, paste0("CVR_", current_reg, ".png"))
  png(cvr_plot_path, width = 800, height = 600)
  forest(cvr_result, 
         slab = current_df_cvr$`First Author_HC`, 
         xlab = "Coefficient of Variation Ratio (CVR)", 
         main = paste("Forest Plot for CVR in", current_reg, "-", "Established Psychosis vs HC"))
  dev.off()

  # VR meta-analysis
  escalc_vr_results <- escalc(measure = "VR", 
                               m1i = current_df$`metabolite mean (bilateral)_Psychosis`,
                               sd1i = current_df$`sd (bilateral)_Psychosis`,
                               n1i = current_df$`sample_size_Psychosis`,
                               m2i = current_df$`metabolite mean (bilateral)_HC`,
                               sd2i = current_df$`sd (bilateral)_HC`,
                               n2i = current_df$`sample_size_HC`)
  current_df_vr <- cbind(current_df, escalc_vr_results)
  vr_result <- rma(yi, vi, data = current_df_vr)

  # Store VR results
  psych_vr_summary_results <- rbind(psych_vr_summary_results, data.frame(
    brain_region = current_reg,
    diagnosis = "Established Psychosis",
    yi = vr_result$beta[1],
    ci.lb = vr_result$ci.lb[1],
    ci.ub = vr_result$ci.ub[1],
    p_value = vr_result$pval,
    I2 = vr_result$I2,
    total_cases = total_cases,
    total_controls = total_controls,
    num_studies = num_studies,
    stringsAsFactors = FALSE
  ))

  # Save VR plot
  vr_plot_path <- file.path(output_folder, paste0("VR_", current_reg, ".png"))
  png(vr_plot_path, width = 800, height = 600)
  forest(vr_result, 
         slab = current_df_vr$`First Author_HC`, 
         xlab = "Variance Ratio (VR)", 
         main = paste("Forest Plot for VR in", current_reg, "-", "Established Psychosis vs HC"))
  dev.off()
}


# Remove duplicate rows if any
psych_smd_summary_results <- psych_smd_summary_results %>% distinct()
psych_cvr_summary_results <- psych_cvr_summary_results %>% distinct()
psych_vr_summary_results <- psych_vr_summary_results %>% distinct()

# Print the summary of meta-analysis results
print(psych_smd_summary_results)
print(psych_cvr_summary_results)
print(psych_vr_summary_results)

# Save results to Excel if needed
write_xlsx(psych_cvr_summary_results, path = "psych_cvr_results.xlsx")
write_xlsx(psych_vr_summary_results, path = "psych_vr_results.xlsx")

```

```{r}
# Funnel plots and Egger's test for combined psychosis group SMD results

# Create an empty data frame to store Egger's test results
eggers_results <- data.frame(
  brain_region = character(),
  egger_test_statistic = numeric(),
  egger_p_value = numeric(),
  stringsAsFactors = FALSE
)

# Loop over each brain region based on the SMD results
for (current_reg in psych_smd_summary_results$brain_region) {
  # Subset the original data for the current brain region
  current_df <- merged_df %>%
    filter(region == current_reg) %>%
    filter(diagnosis %in% c("Psychosis", "HC")) %>%
    select(diagnosis, ID, `metabolite mean (bilateral)`, `sd (bilateral)`, sample_size)

  # Group by study ID 
  current_df <- current_df %>%
    group_by(ID) %>%
    filter(all(c("HC", "Psychosis") %in% diagnosis)) %>%
    ungroup() %>%
    pivot_wider(names_from = diagnosis, 
                values_from = c(`metabolite mean (bilateral)`, `sd (bilateral)`, sample_size)) %>%
    na.omit()

  # Proceed if there are at least two studies for a funnel plot
  if (nrow(current_df) >= 2) {
    # Calculate SMD effect size using escalc
    escalc_smd_results <- escalc(measure = "SMD", 
                                 m1i = current_df$`metabolite mean (bilateral)_Psychosis`,
                                 sd1i = current_df$`sd (bilateral)_Psychosis`,
                                 m2i = current_df$`metabolite mean (bilateral)_HC`,
                                 sd2i = current_df$`sd (bilateral)_HC`,
                                 n1i = current_df$`sample_size_Psychosis`,
                                 n2i = current_df$`sample_size_HC`)
    current_df_smd <- cbind(current_df, escalc_smd_results)
    
    # Meta-analysis for SMD
    smd_result <- rma(yi, vi, data = current_df_smd)
    
    # Funnel plot for SMD
    funnel(smd_result, main = paste("Funnel Plot for SMD in", current_reg, "- Established Psychosis vs HC"))
    
    # Perform Egger's test if there are 10 or more studies
    if (nrow(current_df) >= 10) {
      # Egger's test
      egger_test <- regtest(smd_result, model = "lm", predictor = "sei")
      
      # add Egger's test results to the results data frame
      eggers_results <- rbind(eggers_results, data.frame(
        brain_region = current_reg,
        egger_test_statistic = egger_test$zval,  
        egger_p_value = egger_test$pval,         
        stringsAsFactors = FALSE
      ))
      
      cat("Egger's test for", current_reg, ":\n")
      print(egger_test)
    }
  } else {
    cat("Skipping brain region:", current_reg, "due to insufficient studies.\n")
  }
}

# Merge Egger's results with the SMD summary results
combined_smd_results <- psych_smd_summary_results %>%
  left_join(eggers_results, by = "brain_region")

print(combined_smd_results)

# Save combined results to an Excel file
write_xlsx(combined_smd_results, path = "combined_smd_results_with_eggers.xlsx")

```

```{r}

# TRS - Meta analysis -------

# Create dataframes to store overall SMD, CVR, and VR results 
trs_smd_summary_results <- data.frame(
  brain_region = character(),
  diagnosis = character(),
  yi = numeric(),
  ci.lb = numeric(),
  ci.ub = numeric(),
  p_value = numeric(),
  I2 = numeric(),
  total_cases = numeric(),
  total_controls = numeric(),
  num_studies = integer(),
  stringsAsFactors = FALSE
)

trs_cvr_summary_results <- data.frame(
  brain_region = character(),
  diagnosis = character(),
  yi = numeric(),
  ci.lb = numeric(),
  ci.ub = numeric(),
  p_value = numeric(),
  I2 = numeric(),
  total_cases = numeric(),
  total_controls = numeric(),
  num_studies = integer(),
  stringsAsFactors = FALSE
)

trs_vr_summary_results <- data.frame(
  brain_region = character(),
  diagnosis = character(),
  yi = numeric(),
  ci.lb = numeric(),
  ci.ub = numeric(),
  p_value = numeric(),
  I2 = numeric(),
  total_cases = numeric(),
  total_controls = numeric(),
  num_studies = integer(),
  stringsAsFactors = FALSE
)

# Setting up loop variables ----
reg <- unique(merged_df$region)
diagnoses <- c('TRS', 'HC')

# Create a folder to save the plots
output_folder <- "trs_forest_plots"
if (!dir.exists(output_folder)) {
  dir.create(output_folder)
}

# Loop over each brain region
for (current_reg in reg) {
  cat("Processing brain region:", current_reg, "\n")
  
  # Subset data for the current brain region
  current_df <- merged_df %>%
    filter(region == current_reg, diagnosis %in% diagnoses) %>%
    select(diagnosis, ID, `First Author`, metabolite, region, 
           `metabolite mean (bilateral)`, `sd (bilateral)`, sample_size)

  current_df <- current_df %>%
    group_by(ID) %>%
    filter(all(c("HC", "TRS") %in% diagnosis)) %>%
    ungroup() %>%
    pivot_wider(names_from = diagnosis, values_from = c(`metabolite mean (bilateral)`, `sd (bilateral)`, sample_size, `First Author`)) %>%
    na.omit()

  # Check if there are sufficient studies for analysis
  if (nrow(current_df) < 2) { 
    cat("Skipping brain region:", current_reg, "due to insufficient data.\n")
    next
  }

  # Calculate total cases, controls, and number of studies
  total_cases <- sum(current_df$`sample_size_TRS`, na.rm = TRUE)
  total_controls <- sum(current_df$`sample_size_HC`, na.rm = TRUE)
  num_studies <- nrow(current_df)

  # SMD meta-analysis
  escalc_smd_results <- escalc(measure = "SMD", 
                               m1i = current_df$`metabolite mean (bilateral)_TRS`,
                               sd1i = current_df$`sd (bilateral)_TRS`,
                               m2i = current_df$`metabolite mean (bilateral)_HC`,
                               sd2i = current_df$`sd (bilateral)_HC`,
                               n1i = current_df$`sample_size_TRS`,
                               n2i = current_df$`sample_size_HC`)
  current_df_smd <- cbind(current_df, escalc_smd_results)
  smd_result <- rma(yi, vi, data = current_df_smd)
  
  # Store SMD results
  trs_smd_summary_results <- rbind(trs_smd_summary_results, data.frame(
    brain_region = current_reg,
    diagnosis = "TRS",
    yi = smd_result$beta[1],
    ci.lb = smd_result$ci.lb[1],
    ci.ub = smd_result$ci.ub[1],
    p_value = smd_result$pval,
    I2 = smd_result$I2,
    total_cases = total_cases,
    total_controls = total_controls,
    num_studies = num_studies,
    stringsAsFactors = FALSE
  ))

  # Save SMD plot
  smd_plot_path <- file.path(output_folder, paste0("SMD_", current_reg, ".png"))
  png(smd_plot_path, width = 800, height = 600)
  forest(smd_result, 
         slab = current_df_smd$`First Author_HC`, 
         xlab = "Standardized Mean Difference (SMD)", 
         main = paste("Forest Plot for SMD in", current_reg, "-", "TRS vs HC"))
  dev.off()

  # CVR meta-analysis
  escalc_cvr_results <- escalc(measure = "CVR", 
                               m1i = current_df$`metabolite mean (bilateral)_TRS`,
                               sd1i = current_df$`sd (bilateral)_TRS`,
                               n1i = current_df$`sample_size_TRS`,
                               m2i = current_df$`metabolite mean (bilateral)_HC`,
                               sd2i = current_df$`sd (bilateral)_HC`,
                               n2i = current_df$`sample_size_HC`)
  current_df_cvr <- cbind(current_df, escalc_cvr_results)
  cvr_result <- rma(yi, vi, data = current_df_cvr)

  # Store CVR results
  trs_cvr_summary_results <- rbind(trs_cvr_summary_results, data.frame(
    brain_region = current_reg,
    diagnosis = "TRS",
    yi = cvr_result$beta[1],
    ci.lb = cvr_result$ci.lb[1],
    ci.ub = cvr_result$ci.ub[1],
    p_value = cvr_result$pval,
    I2 = cvr_result$I2,
    total_cases = total_cases,
    total_controls = total_controls,
    num_studies = num_studies,
    stringsAsFactors = FALSE
  ))

  # Save CVR plot
  cvr_plot_path <- file.path(output_folder, paste0("CVR_", current_reg, ".png"))
  png(cvr_plot_path, width = 800, height = 600)
  forest(cvr_result, 
         slab = current_df_cvr$`First Author_HC`, 
         xlab = "Coefficient of Variation Ratio (CVR)", 
         main = paste("Forest Plot for CVR in", current_reg, "-", "TRS vs HC"))
  dev.off()

  # VR meta-analysis
  escalc_vr_results <- escalc(measure = "VR", 
                               m1i = current_df$`metabolite mean (bilateral)_TRS`,
                               sd1i = current_df$`sd (bilateral)_TRS`,
                               n1i = current_df$`sample_size_TRS`,
                               m2i = current_df$`metabolite mean (bilateral)_HC`,
                               sd2i = current_df$`sd (bilateral)_HC`,
                               n2i = current_df$`sample_size_HC`)
  current_df_vr <- cbind(current_df, escalc_vr_results)
  vr_result <- rma(yi, vi, data = current_df_vr)

  # Store VR results
  trs_vr_summary_results <- rbind(trs_vr_summary_results, data.frame(
    brain_region = current_reg,
    diagnosis = "TRS",
    yi = vr_result$beta[1],
    ci.lb = vr_result$ci.lb[1],
    ci.ub = vr_result$ci.ub[1],
    p_value = vr_result$pval,
    I2 = vr_result$I2,
    total_cases = total_cases,
    total_controls = total_controls,
    num_studies = num_studies,
    stringsAsFactors = FALSE
  ))

  # Save VR plot
  vr_plot_path <- file.path(output_folder, paste0("VR_", current_reg, ".png"))
  png(vr_plot_path, width = 800, height = 600)
  forest(vr_result, 
         slab = current_df_vr$`First Author_HC`, 
         xlab = "Variance Ratio (VR)", 
         main = paste("Forest Plot for VR in", current_reg, "-", "TRS vs HC"))
  dev.off()
}

# Remove duplicate rows if any
trs_smd_summary_results <- trs_smd_summary_results %>% distinct()
trs_cvr_summary_results <- trs_cvr_summary_results %>% distinct()
trs_vr_summary_results <- trs_vr_summary_results %>% distinct()

# Print the summary of meta-analysis results
print(trs_smd_summary_results)
print(trs_cvr_summary_results)
print(trs_vr_summary_results)

# Save the summary data frames to Excel files if needed
write_xlsx(trs_smd_summary_results, path = "trs_smd_results.xlsx")
write_xlsx(trs_cvr_summary_results, path = "trs_cvr_results.xlsx")
write_xlsx(trs_vr_summary_results, path = "trs_vr_results.xlsx")

# not enough for Egger's
```


```{r}

# Combine the SMD dataframes for plotting
established_psych_combined_smd_results <- bind_rows(
  chr_smd_summary_results,
  psych_smd_summary_results,
  trs_smd_summary_results
)

# Combine the CVR dataframes for plotting
combined_cvr_results <- bind_rows(
  chr_cvr_summary_results,
  psych_cvr_summary_results,
  trs_cvr_summary_results
)

# Combine the VR dataframes for plotting
combined_vr_results <- bind_rows(
  chr_vr_summary_results,
  psych_vr_summary_results,
  trs_vr_summary_results
)

```


```{r}
# Plotting - SMD established psychosis  vs HCs - Figure 4

# Specify the order of brain regions from cortical to subcortical and then reverse it
region_order <- c("dlPFC", "mPFC", "Other frontal lobe", "ACC", "PCC", "Temporal lobe", "Parietal lobe", "Occipital lobe", 
                  "Global grey matter", "Global white matter", "Frontal white matter", "Corpus callosum", "Centrum semiovale", 
                  "Cerebellum", "Striatum", "Thalamus", "Hippocampus")
region_order <- rev(region_order)
established_psych_combined_smd_results$diagnosis[is.na(established_psych_combined_smd_results$diagnosis)] <- "Established Psychosis"
established_psych_combined_smd_results$brain_region <- factor(established_psych_combined_smd_results$brain_region, levels = region_order)


# Specify legend order for diagnosis categories
diagnosis_order <- c("CHR", "Established Psychosis", "TRS")
diagnosis_order <- rev(diagnosis_order)
established_psych_combined_smd_results$diagnosis <- factor(established_psych_combined_smd_results$diagnosis, levels = diagnosis_order)

# Create a dummy data frame to ensure consistent spacing between bars
dummy_data <- expand.grid(
  brain_region = levels(established_psych_combined_smd_results$brain_region),
  diagnosis = diagnosis_order
)
plot_data <- merge(dummy_data, established_psych_combined_smd_results, all.x = TRUE)

# create figure 3
next_bar_plot <- ggplot(plot_data, aes(x = yi, y = brain_region, fill = diagnosis)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8), color = "black", width = 1.1) + 
  geom_errorbar(aes(xmin = ci.lb, xmax = ci.ub), position = position_dodge(width = 0.8), width = 0.3) +
  theme_minimal(base_size = 15) + 
  labs(
    title = "Choline Levels by Brain Region and Diagnosis",
    x = "Standardised Mean Difference (SMD)",
    y = "Brain Region",
    fill = ""
  ) +
  theme(
    axis.text.y = element_text(angle = 0, hjust = 1, size = 8),
    axis.text.x = element_text(angle = 0, hjust = 1, size = 10),
    axis.title.y = element_text(size = 10, face = "bold", margin = margin(r = 10)),  # space on the right of y-axis title
    axis.title.x = element_text(size = 10, face = "bold", margin = margin(t = 10)),  # space on the top of x-axis title
    plot.title = element_text(size = 10, face = "bold", hjust = 0.5, margin = margin(b = 2)), 
    legend.position = "top",   
    legend.text = element_text(size = 8),  
    legend.title = element_text(size = 8, face = "bold"), 
    legend.key.size = unit(0.4, "cm"),  
    legend.spacing.y = unit(-0.5, "cm"),  # spacing between legend and plot
    legend.margin = margin(t = 2, b = 0),  # space above the legend
    panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), 
    panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "lightgrey"),
    plot.margin = unit(c(1, 1, 1, 1), "cm")   
  ) +
    scale_x_continuous(breaks = seq(-0.5, 1, by = 0.5)) + 
  scale_fill_manual(values = brewer.pal(n = 5, name = "Set2"), guide = guide_legend(reverse = TRUE)) 

print(next_bar_plot)
ggsave("figure3.png", plot = next_bar_plot, width = 7, height = 6.5, dpi = 300, bg = "white")

```

```{r}
# CVR established psychosis - Figure 4
# Specify the order of brain regions from cortical to subcortical and then reverse it
region_order <- c("dlPFC", "mPFC", "Other frontal lobe", "ACC", "PCC", "Temporal lobe", "Parietal lobe", "Occipital lobe", 
                  "Global grey matter", "Global white matter", "Frontal white matter", "Corpus callosum", "Centrum semiovale", 
                  "Cerebellum", "Striatum", "Thalamus", "Hippocampus")
region_order <- rev(region_order)
combined_cvr_results$brain_region <- factor(combined_cvr_results$brain_region, levels = region_order)

# Order of diagnosis categories
diagnosis_order <- c("CHR", "Established Psychosis", "TRS")
diagnosis_order <- rev(diagnosis_order)
combined_cvr_results$diagnosis <- factor(combined_cvr_results$diagnosis, levels = diagnosis_order)

# Create a dummy data frame to ensure consistent spacing of bars
dummy_data <- expand.grid(
  brain_region = levels(combined_cvr_results$brain_region),
  diagnosis = diagnosis_order
)
plot_data <- merge(dummy_data, combined_cvr_results, all.x = TRUE)

# Create Figure 4
cvr_bar_plot <- ggplot(plot_data, aes(x = yi, y = brain_region, fill = diagnosis)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8), color = "black", width = 1.1) +  
  geom_errorbar(aes(xmin = ci.lb, xmax = ci.ub), position = position_dodge(width = 0.8), width = 0.3) +
  theme_minimal(base_size = 15) +  
  labs(
    title = "Choline Variability (CVR) by Brain Region and Diagnosis",
    x = "CVR",
    y = "Brain Region",
    fill = ""
  ) +
  theme(
    axis.text.y = element_text(angle = 0, hjust = 1, size = 8),
    axis.text.x = element_text(angle = 0, hjust = 1, size = 10),
    axis.title.y = element_text(size = 10, face = "bold", margin = margin(r = 10)),   
    axis.title.x = element_text(size = 10, face = "bold", margin = margin(t = 10)),   
    plot.title = element_text(size = 10, face = "bold", hjust = 0.5, margin = margin(b = 2)),  
    legend.position = "top",  
    legend.text = element_text(size = 8),  
    legend.title = element_text(size = 8, face = "bold"),  
    legend.key.size = unit(0.4, "cm"),  
    legend.spacing.y = unit(-0.5, "cm"),   
    legend.margin = margin(t = 2, b = 0),   
    panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), 
    panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "lightgrey"),
    plot.margin = unit(c(1, 1, 1, 1), "cm")  
  ) +
    scale_x_continuous(breaks = seq(-3, 1, by = 1), limits = c(-2, 2)) +  
  scale_fill_manual(values = brewer.pal(n = 5, name = "Set2"), guide = guide_legend(reverse = TRUE))  

print(cvr_bar_plot)
ggsave("figure4.png", plot = cvr_bar_plot, width = 7, height = 6.5, dpi = 300, bg = "white")

```